name: 'Go - JWT Continous Integration'

on:
  push:
    branches:
     - master
     - dev
  pull_request:
    branches:
     - master
jobs:
 test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        go: ['1.14', '1.15']
    name: Test
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{matrix.go}}
      - uses: actions/checkout@v2
        name: 'Checkout'
      - run: go test ./... -race -covermode=atomic -coverprofile=coverage.txt
      - uses: codecov/codecov-action@v1 
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt 
          flags: unittests 
          name: codecov-umbrella 
          fail_ci_if_error: true
          verbose: true